* [32mdevel[m
  [31mremotes/origin/HEAD[m -> origin/devel
  [31mremotes/origin/araq-atomic-loads[m
  [31mremotes/origin/araq-carry-flag[m
  [31mremotes/origin/araq-fixes-15533[m
  [31mremotes/origin/araq-fixes-22479[m
  [31mremotes/origin/araq-fixes-25037[m
  [31mremotes/origin/araq-generic-inst-fix[m
  [31mremotes/origin/araq-loadfromfield[m
  [31mremotes/origin/araq-orc-hotfix[m
  [31mremotes/origin/araq-pipeline[m
  [31mremotes/origin/araq-quirky-boots[m
  [31mremotes/origin/devel[m
  [31mremotes/origin/fix_15097[m
  [31mremotes/origin/gh-pages[m
  [31mremotes/origin/lto[m
  [31mremotes/origin/pr_#22560[m
  [31mremotes/origin/pr_16253[m
  [31mremotes/origin/pr_ast2ir[m
  [31mremotes/origin/pr_best_efforts[m
  [31mremotes/origin/pr_build_types[m
  [31mremotes/origin/pr_clean_up_sink[m
  [31mremotes/origin/pr_copy_23610[m
  [31mremotes/origin/pr_disable_sink[m
  [31mremotes/origin/pr_discardable_refactor[m
  [31mremotes/origin/pr_distinct_ctype_alias[m
  [31mremotes/origin/pr_distinct_ctypes[m
  [31mremotes/origin/pr_error_message[m
  [31mremotes/origin/pr_fix_abi_mem_order[m
  [31mremotes/origin/pr_fix_signature[m
  [31mremotes/origin/pr_fold_unfold[m
  [31mremotes/origin/pr_forward[m
  [31mremotes/origin/pr_gcc_14[m
  [31mremotes/origin/pr_holey_enum[m
  [31mremotes/origin/pr_legacy_asm[m
  [31mremotes/origin/pr_move_system[m
  [31mremotes/origin/pr_no_forward_decl[m
  [31mremotes/origin/pr_nodecl_type[m
  [31mremotes/origin/pr_object[m
  [31mremotes/origin/pr_packed_refactor[m
  [31mremotes/origin/pr_pcre_re[m
  [31mremotes/origin/pr_private_type_node[m
  [31mremotes/origin/pr_quote_do_r[m
  [31mremotes/origin/pr_recursive_strict_effects[m
  [31mremotes/origin/pr_refc_copy[m
  [31mremotes/origin/pr_remove_cyclics[m
  [31mremotes/origin/pr_remove_macros[m
  [31mremotes/origin/pr_shadowing[m
  [31mremotes/origin/pr_string_v3[m
  [31mremotes/origin/pr_table_sinks[m
  [31mremotes/origin/pr_tables_lent_iter[m
  [31mremotes/origin/pr_ungeduldig[m
  [31mremotes/origin/pr_union_cast[m
  [31mremotes/origin/revert-24809-pr_eval_ccg[m
  [31mremotes/origin/revert-25016-pr_test_re[m
  [31mremotes/origin/ringabout-patch-3[m
  [31mremotes/origin/ringabout-patch-9[m
  [31mremotes/origin/version-0-19[m
  [31mremotes/origin/version-0-20[m
  [31mremotes/origin/version-1-0[m
  [31mremotes/origin/version-1-2[m
  [31mremotes/origin/version-1-4[m
  [31mremotes/origin/version-1-6[m
  [31mremotes/origin/version-2-0[m
  [31mremotes/origin/version-2-2[m
  [31mremotes/origin/version-20-staging[m
  [31mremotes/origin/version-22-staging[m
