steps:
  - id: 'build-docker-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/skinlensr-frontend'
      - '-f'
      - 'SkinLensR/SkinLensR/frontend/Dockerfile'
      - 'SkinLensR/SkinLensR/frontend'

images:
  - 'gcr.io/$PROJECT_ID/skinlensr-frontend'

options:
  machineType: 'N1_HIGHCPU_8'
