"""Add legal documents and user agreements tables

Revision ID: 27a519208a33
Revises: 503b815983f6
Create Date: 2025-07-28 21:08:28.619944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a519208a33'
down_revision: Union[str, None] = '503b815983f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_index(op.f('ix_legal_documents_language'), 'legal_documents', ['language'], unique=False)
    op.create_index(op.f('ix_legal_documents_type'), 'legal_documents', ['type'], unique=False)
    op.create_index(op.f('ix_legal_documents_version'), 'legal_documents', ['version'], unique=True)
    op.create_table('user_legal_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('agreed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_latest_version_agreed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['legal_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_legal_agreements_document_id'), 'user_legal_agreements', ['document_id'], unique=False)
    op.create_index(op.f('ix_user_legal_agreements_id'), 'user_legal_agreements', ['id'], unique=False)
    op.create_index(op.f('ix_user_legal_agreements_user_id'), 'user_legal_agreements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_legal_agreements_user_id'), table_name='user_legal_agreements')
    op.drop_index(op.f('ix_user_legal_agreements_id'), table_name='user_legal_agreements')
    op.drop_index(op.f('ix_user_legal_agreements_document_id'), table_name='user_legal_agreements')
    op.drop_table('user_legal_agreements')
    op.drop_index(op.f('ix_legal_documents_version'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_type'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_language'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_table('legal_documents')
    # ### end Alembic commands ###
