"""Mise à jours des modifications Api et endpoints 

Revision ID: 47e6d4fbbda1
Revises: 8107e4adf123
Create Date: 2025-08-09 08:09:04.202212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47e6d4fbbda1'
down_revision: Union[str, None] = '8107e4adf123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_legal_documents')

    # Conversion explicite avant modification
    op.execute("ALTER TABLE legal_documents ALTER COLUMN version TYPE INTEGER USING version::integer")

    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        # Plus besoin de modifier 'version' ici, c'est fait en SQL direct
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_index('ix_legal_documents_language')
        batch_op.drop_index('ix_legal_documents_type')
        batch_op.drop_index('ix_legal_documents_version')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion', sa.Float(), nullable=False))
        batch_op.drop_constraint('progress_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('step')
        batch_op.drop_column('completed')

    with op.batch_alter_table('user_legal_agreements', schema=None) as batch_op:
        batch_op.alter_column('is_latest_version_agreed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_user_legal_agreements_document_id')
        batch_op.drop_index('ix_user_legal_agreements_user_id')
        batch_op.drop_constraint('user_legal_agreements_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_legal_agreements_document_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'legal_documents', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('agreed_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_legal_agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_legal_agreements_document_id_fkey', 'legal_documents', ['document_id'], ['id'])
        batch_op.create_foreign_key('user_legal_agreements_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_index('ix_user_legal_agreements_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_legal_agreements_document_id', ['document_id'], unique=False)
        batch_op.alter_column('is_latest_version_agreed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('step', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('progress_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('completion')

    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.create_index('ix_legal_documents_version', ['version'], unique=False)
        batch_op.create_index('ix_legal_documents_type', ['type'], unique=False)
        batch_op.create_index('ix_legal_documents_language', ['language'], unique=False)
        batch_op.alter_column('content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.create_table('agent_legal_documents',
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('legal_document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_legal_documents_agent_id_fkey'),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_documents.id'], name='agent_legal_documents_legal_document_id_fkey'),
    sa.PrimaryKeyConstraint('agent_id', 'legal_document_id', name='agent_legal_documents_pkey')
    )
    # ### end Alembic commands ###
