"""Ajout des champs utilisateur

Revision ID: 60355fa971a5
Revises: 97e5f5dd349a
Create Date: 2025-08-05 16:11:17.289613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60355fa971a5'
down_revision: Union[str, None] = '97e5f5dd349a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_legal_agreements', 'agreed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_legal_agreements', 'is_latest_version_agreed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('user_legal_agreements_user_id_fkey', 'user_legal_agreements', type_='foreignkey')
    op.drop_constraint('user_legal_agreements_document_id_fkey', 'user_legal_agreements', type_='foreignkey')
    op.create_foreign_key(None, 'user_legal_agreements', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_legal_agreements', 'legal_documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_legal_agreements', type_='foreignkey')
    op.drop_constraint(None, 'user_legal_agreements', type_='foreignkey')
    op.create_foreign_key('user_legal_agreements_document_id_fkey', 'user_legal_agreements', 'legal_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_legal_agreements_user_id_fkey', 'user_legal_agreements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_legal_agreements', 'is_latest_version_agreed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_legal_agreements', 'agreed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
