"""Ajoute username et password

Revision ID: f33059fcec7c
Revises: 43eda02bde95
Create Date: 2025-08-02 00:17:15.776832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33059fcec7c'
down_revision: Union[str, None] = '43eda02bde95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_documents_version', table_name='legal_documents')
    op.create_index(op.f('ix_legal_documents_version'), 'legal_documents', ['version'], unique=False)
    op.create_unique_constraint('uq_legal_document_type_version_lang', 'legal_documents', ['type', 'version', 'language'])
    op.alter_column('user_legal_agreements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_legal_agreements', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_legal_agreements', 'agreed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_legal_agreements', 'is_latest_version_agreed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('user_legal_agreements_user_id_fkey', 'user_legal_agreements', type_='foreignkey')
    op.drop_constraint('user_legal_agreements_document_id_fkey', 'user_legal_agreements', type_='foreignkey')
    op.create_foreign_key(None, 'user_legal_agreements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_legal_agreements', 'legal_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'user_legal_agreements', type_='foreignkey')
    op.drop_constraint(None, 'user_legal_agreements', type_='foreignkey')
    op.create_foreign_key('user_legal_agreements_document_id_fkey', 'user_legal_agreements', 'legal_documents', ['document_id'], ['id'])
    op.create_foreign_key('user_legal_agreements_user_id_fkey', 'user_legal_agreements', 'users', ['user_id'], ['id'])
    op.alter_column('user_legal_agreements', 'is_latest_version_agreed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_legal_agreements', 'agreed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_legal_agreements', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_legal_agreements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_legal_document_type_version_lang', 'legal_documents', type_='unique')
    op.drop_index(op.f('ix_legal_documents_version'), table_name='legal_documents')
    op.create_index('ix_legal_documents_version', 'legal_documents', ['version'], unique=True)
    # ### end Alembic commands ###
